Jenkinsfile: Convert to Declarative Pipeline (#8)
* Jenkinsfile: Convert to Declarative Pipeline

* Update README.md

* Jenkinsfile: Use pipeline properties

See http://stackoverflow.com/questions/35370810/how-do-i-use-jenkins-pipeline-properties-step

* Jenkinsfile: properties are now called "options"

See runtime error:

```
Started by user Admin (itm-gmacario-w7)
Obtained Jenkinsfile from git https://github.com/gmacario/jenkins-build-agl-distro
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 2: The properties section has been renamed as of version 0.8. Use options instead. @ line 2, column 3.
     properties([
     ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1073)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:591)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:569)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:546)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:67)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:430)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:393)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:238)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Finished: FAILURE
```

Signed-off-by: Gianpaolo Macario <gianpaolo_macario@mentor.com>

* Jenkins: Fix (hopefully) pipeline parameters

See https://jenkins.io/doc/book/pipeline/syntax/

Signed-off-by: Gianpaolo Macario <gianpaolo_macario@mentor.com>

* Jenkinsfile: Add missing comma

Signed-off-by: Gianpaolo Macario <gianpaolo_macario@mentor.com>

* Jenkinsfile: Yet another fix to please Jenkins :-(

Signed-off-by: Gianpaolo Macario <gianpaolo_macario@mentor.com>

* Jenkinsfile: Yet another syntax fix

Groovy is really picky...

Signed-off-by: Gianpaolo Macario <gianpaolo_macario@mentor.com>

* Jenkinsfile: Enclose parameters in quotes

Signed-off-by: Gianpaolo Macario <gianpaolo_macario@mentor.com>

* README.md: Build master branch

Signed-off-by: Gianpaolo Macario <gianpaolo_macario@mentor.com>